name: 'JEsperancinhaOrg Android Action'
description: 'Allows usage of the Android SDK in GitHub Pipelines'
author: 'João Esperancinha <jofisaes@gmail.com>'
branding:
    icon: 'package'
    color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
